// Code generated by ent, DO NOT EDIT.

package guestkey

import (
	"keeper/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLTE(FieldID, id))
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldAppID, v))
}

// DivisionID applies equality check predicate on the "division_id" field. It's identical to DivisionIDEQ.
func DivisionID(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldDivisionID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldUserID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldName, v))
}

// SiteKey applies equality check predicate on the "site_key" field. It's identical to SiteKeyEQ.
func SiteKey(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldSiteKey, v))
}

// Domain applies equality check predicate on the "domain" field. It's identical to DomainEQ.
func Domain(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldDomain, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int8) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldAppID, v))
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNEQ(FieldAppID, v))
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldIn(FieldAppID, vs...))
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNotIn(FieldAppID, vs...))
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGT(FieldAppID, v))
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGTE(FieldAppID, v))
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLT(FieldAppID, v))
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLTE(FieldAppID, v))
}

// DivisionIDEQ applies the EQ predicate on the "division_id" field.
func DivisionIDEQ(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldDivisionID, v))
}

// DivisionIDNEQ applies the NEQ predicate on the "division_id" field.
func DivisionIDNEQ(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNEQ(FieldDivisionID, v))
}

// DivisionIDIn applies the In predicate on the "division_id" field.
func DivisionIDIn(vs ...int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldIn(FieldDivisionID, vs...))
}

// DivisionIDNotIn applies the NotIn predicate on the "division_id" field.
func DivisionIDNotIn(vs ...int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNotIn(FieldDivisionID, vs...))
}

// DivisionIDGT applies the GT predicate on the "division_id" field.
func DivisionIDGT(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGT(FieldDivisionID, v))
}

// DivisionIDGTE applies the GTE predicate on the "division_id" field.
func DivisionIDGTE(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGTE(FieldDivisionID, v))
}

// DivisionIDLT applies the LT predicate on the "division_id" field.
func DivisionIDLT(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLT(FieldDivisionID, v))
}

// DivisionIDLTE applies the LTE predicate on the "division_id" field.
func DivisionIDLTE(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLTE(FieldDivisionID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLTE(FieldUserID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldContainsFold(FieldName, v))
}

// SiteKeyEQ applies the EQ predicate on the "site_key" field.
func SiteKeyEQ(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldSiteKey, v))
}

// SiteKeyNEQ applies the NEQ predicate on the "site_key" field.
func SiteKeyNEQ(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNEQ(FieldSiteKey, v))
}

// SiteKeyIn applies the In predicate on the "site_key" field.
func SiteKeyIn(vs ...string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldIn(FieldSiteKey, vs...))
}

// SiteKeyNotIn applies the NotIn predicate on the "site_key" field.
func SiteKeyNotIn(vs ...string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNotIn(FieldSiteKey, vs...))
}

// SiteKeyGT applies the GT predicate on the "site_key" field.
func SiteKeyGT(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGT(FieldSiteKey, v))
}

// SiteKeyGTE applies the GTE predicate on the "site_key" field.
func SiteKeyGTE(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGTE(FieldSiteKey, v))
}

// SiteKeyLT applies the LT predicate on the "site_key" field.
func SiteKeyLT(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLT(FieldSiteKey, v))
}

// SiteKeyLTE applies the LTE predicate on the "site_key" field.
func SiteKeyLTE(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLTE(FieldSiteKey, v))
}

// SiteKeyContains applies the Contains predicate on the "site_key" field.
func SiteKeyContains(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldContains(FieldSiteKey, v))
}

// SiteKeyHasPrefix applies the HasPrefix predicate on the "site_key" field.
func SiteKeyHasPrefix(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldHasPrefix(FieldSiteKey, v))
}

// SiteKeyHasSuffix applies the HasSuffix predicate on the "site_key" field.
func SiteKeyHasSuffix(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldHasSuffix(FieldSiteKey, v))
}

// SiteKeyEqualFold applies the EqualFold predicate on the "site_key" field.
func SiteKeyEqualFold(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEqualFold(FieldSiteKey, v))
}

// SiteKeyContainsFold applies the ContainsFold predicate on the "site_key" field.
func SiteKeyContainsFold(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldContainsFold(FieldSiteKey, v))
}

// DomainEQ applies the EQ predicate on the "domain" field.
func DomainEQ(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldDomain, v))
}

// DomainNEQ applies the NEQ predicate on the "domain" field.
func DomainNEQ(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNEQ(FieldDomain, v))
}

// DomainIn applies the In predicate on the "domain" field.
func DomainIn(vs ...string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldIn(FieldDomain, vs...))
}

// DomainNotIn applies the NotIn predicate on the "domain" field.
func DomainNotIn(vs ...string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNotIn(FieldDomain, vs...))
}

// DomainGT applies the GT predicate on the "domain" field.
func DomainGT(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGT(FieldDomain, v))
}

// DomainGTE applies the GTE predicate on the "domain" field.
func DomainGTE(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGTE(FieldDomain, v))
}

// DomainLT applies the LT predicate on the "domain" field.
func DomainLT(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLT(FieldDomain, v))
}

// DomainLTE applies the LTE predicate on the "domain" field.
func DomainLTE(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLTE(FieldDomain, v))
}

// DomainContains applies the Contains predicate on the "domain" field.
func DomainContains(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldContains(FieldDomain, v))
}

// DomainHasPrefix applies the HasPrefix predicate on the "domain" field.
func DomainHasPrefix(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldHasPrefix(FieldDomain, v))
}

// DomainHasSuffix applies the HasSuffix predicate on the "domain" field.
func DomainHasSuffix(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldHasSuffix(FieldDomain, v))
}

// DomainEqualFold applies the EqualFold predicate on the "domain" field.
func DomainEqualFold(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEqualFold(FieldDomain, v))
}

// DomainContainsFold applies the ContainsFold predicate on the "domain" field.
func DomainContainsFold(v string) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldContainsFold(FieldDomain, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int8) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int8) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int8) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int8) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int8) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int8) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int8) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int8) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLTE(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GuestKey {
	return predicate.GuestKey(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GuestKey) predicate.GuestKey {
	return predicate.GuestKey(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GuestKey) predicate.GuestKey {
	return predicate.GuestKey(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GuestKey) predicate.GuestKey {
	return predicate.GuestKey(sql.NotPredicates(p))
}
