// Code generated by ent, DO NOT EDIT.

package impersonationsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the impersonationsession type in the database.
	Label = "impersonation_session"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldDivisionID holds the string denoting the division_id field in the database.
	FieldDivisionID = "division_id"
	// FieldImpersonatorUserID holds the string denoting the impersonator_user_id field in the database.
	FieldImpersonatorUserID = "impersonator_user_id"
	// FieldTargetUserID holds the string denoting the target_user_id field in the database.
	FieldTargetUserID = "target_user_id"
	// FieldAudience holds the string denoting the audience field in the database.
	FieldAudience = "audience"
	// FieldReadOnly holds the string denoting the read_only field in the database.
	FieldReadOnly = "read_only"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldRevokedAt holds the string denoting the revoked_at field in the database.
	FieldRevokedAt = "revoked_at"
	// Table holds the table name of the impersonationsession in the database.
	Table = "kpr_impersonation_session"
)

// Columns holds all SQL columns for impersonationsession fields.
var Columns = []string{
	FieldID,
	FieldSessionID,
	FieldAppID,
	FieldDivisionID,
	FieldImpersonatorUserID,
	FieldTargetUserID,
	FieldAudience,
	FieldReadOnly,
	FieldReason,
	FieldStatus,
	FieldCreatedAt,
	FieldExpiresAt,
	FieldRevokedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultReadOnly holds the default value on creation for the "read_only" field.
	DefaultReadOnly bool
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int8
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the ImpersonationSession queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// ByAppID orders the results by the app_id field.
func ByAppID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppID, opts...).ToFunc()
}

// ByDivisionID orders the results by the division_id field.
func ByDivisionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDivisionID, opts...).ToFunc()
}

// ByImpersonatorUserID orders the results by the impersonator_user_id field.
func ByImpersonatorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImpersonatorUserID, opts...).ToFunc()
}

// ByTargetUserID orders the results by the target_user_id field.
func ByTargetUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetUserID, opts...).ToFunc()
}

// ByAudience orders the results by the audience field.
func ByAudience(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAudience, opts...).ToFunc()
}

// ByReadOnly orders the results by the read_only field.
func ByReadOnly(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReadOnly, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByRevokedAt orders the results by the revoked_at field.
func ByRevokedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevokedAt, opts...).ToFunc()
}
