// Code generated by ent, DO NOT EDIT.

package impersonationsession

import (
	"keeper/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLTE(FieldID, id))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldSessionID, v))
}

// AppID applies equality check predicate on the "app_id" field. It's identical to AppIDEQ.
func AppID(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldAppID, v))
}

// DivisionID applies equality check predicate on the "division_id" field. It's identical to DivisionIDEQ.
func DivisionID(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldDivisionID, v))
}

// ImpersonatorUserID applies equality check predicate on the "impersonator_user_id" field. It's identical to ImpersonatorUserIDEQ.
func ImpersonatorUserID(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldImpersonatorUserID, v))
}

// TargetUserID applies equality check predicate on the "target_user_id" field. It's identical to TargetUserIDEQ.
func TargetUserID(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldTargetUserID, v))
}

// Audience applies equality check predicate on the "audience" field. It's identical to AudienceEQ.
func Audience(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldAudience, v))
}

// ReadOnly applies equality check predicate on the "read_only" field. It's identical to ReadOnlyEQ.
func ReadOnly(v bool) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldReadOnly, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldReason, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v int8) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldCreatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldExpiresAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldRevokedAt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldContainsFold(FieldSessionID, v))
}

// AppIDEQ applies the EQ predicate on the "app_id" field.
func AppIDEQ(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldAppID, v))
}

// AppIDNEQ applies the NEQ predicate on the "app_id" field.
func AppIDNEQ(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNEQ(FieldAppID, v))
}

// AppIDIn applies the In predicate on the "app_id" field.
func AppIDIn(vs ...int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldIn(FieldAppID, vs...))
}

// AppIDNotIn applies the NotIn predicate on the "app_id" field.
func AppIDNotIn(vs ...int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNotIn(FieldAppID, vs...))
}

// AppIDGT applies the GT predicate on the "app_id" field.
func AppIDGT(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGT(FieldAppID, v))
}

// AppIDGTE applies the GTE predicate on the "app_id" field.
func AppIDGTE(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGTE(FieldAppID, v))
}

// AppIDLT applies the LT predicate on the "app_id" field.
func AppIDLT(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLT(FieldAppID, v))
}

// AppIDLTE applies the LTE predicate on the "app_id" field.
func AppIDLTE(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLTE(FieldAppID, v))
}

// DivisionIDEQ applies the EQ predicate on the "division_id" field.
func DivisionIDEQ(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldDivisionID, v))
}

// DivisionIDNEQ applies the NEQ predicate on the "division_id" field.
func DivisionIDNEQ(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNEQ(FieldDivisionID, v))
}

// DivisionIDIn applies the In predicate on the "division_id" field.
func DivisionIDIn(vs ...int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldIn(FieldDivisionID, vs...))
}

// DivisionIDNotIn applies the NotIn predicate on the "division_id" field.
func DivisionIDNotIn(vs ...int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNotIn(FieldDivisionID, vs...))
}

// DivisionIDGT applies the GT predicate on the "division_id" field.
func DivisionIDGT(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGT(FieldDivisionID, v))
}

// DivisionIDGTE applies the GTE predicate on the "division_id" field.
func DivisionIDGTE(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGTE(FieldDivisionID, v))
}

// DivisionIDLT applies the LT predicate on the "division_id" field.
func DivisionIDLT(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLT(FieldDivisionID, v))
}

// DivisionIDLTE applies the LTE predicate on the "division_id" field.
func DivisionIDLTE(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLTE(FieldDivisionID, v))
}

// ImpersonatorUserIDEQ applies the EQ predicate on the "impersonator_user_id" field.
func ImpersonatorUserIDEQ(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldImpersonatorUserID, v))
}

// ImpersonatorUserIDNEQ applies the NEQ predicate on the "impersonator_user_id" field.
func ImpersonatorUserIDNEQ(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNEQ(FieldImpersonatorUserID, v))
}

// ImpersonatorUserIDIn applies the In predicate on the "impersonator_user_id" field.
func ImpersonatorUserIDIn(vs ...int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldIn(FieldImpersonatorUserID, vs...))
}

// ImpersonatorUserIDNotIn applies the NotIn predicate on the "impersonator_user_id" field.
func ImpersonatorUserIDNotIn(vs ...int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNotIn(FieldImpersonatorUserID, vs...))
}

// ImpersonatorUserIDGT applies the GT predicate on the "impersonator_user_id" field.
func ImpersonatorUserIDGT(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGT(FieldImpersonatorUserID, v))
}

// ImpersonatorUserIDGTE applies the GTE predicate on the "impersonator_user_id" field.
func ImpersonatorUserIDGTE(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGTE(FieldImpersonatorUserID, v))
}

// ImpersonatorUserIDLT applies the LT predicate on the "impersonator_user_id" field.
func ImpersonatorUserIDLT(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLT(FieldImpersonatorUserID, v))
}

// ImpersonatorUserIDLTE applies the LTE predicate on the "impersonator_user_id" field.
func ImpersonatorUserIDLTE(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLTE(FieldImpersonatorUserID, v))
}

// TargetUserIDEQ applies the EQ predicate on the "target_user_id" field.
func TargetUserIDEQ(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldTargetUserID, v))
}

// TargetUserIDNEQ applies the NEQ predicate on the "target_user_id" field.
func TargetUserIDNEQ(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNEQ(FieldTargetUserID, v))
}

// TargetUserIDIn applies the In predicate on the "target_user_id" field.
func TargetUserIDIn(vs ...int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldIn(FieldTargetUserID, vs...))
}

// TargetUserIDNotIn applies the NotIn predicate on the "target_user_id" field.
func TargetUserIDNotIn(vs ...int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNotIn(FieldTargetUserID, vs...))
}

// TargetUserIDGT applies the GT predicate on the "target_user_id" field.
func TargetUserIDGT(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGT(FieldTargetUserID, v))
}

// TargetUserIDGTE applies the GTE predicate on the "target_user_id" field.
func TargetUserIDGTE(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGTE(FieldTargetUserID, v))
}

// TargetUserIDLT applies the LT predicate on the "target_user_id" field.
func TargetUserIDLT(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLT(FieldTargetUserID, v))
}

// TargetUserIDLTE applies the LTE predicate on the "target_user_id" field.
func TargetUserIDLTE(v int) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLTE(FieldTargetUserID, v))
}

// AudienceEQ applies the EQ predicate on the "audience" field.
func AudienceEQ(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldAudience, v))
}

// AudienceNEQ applies the NEQ predicate on the "audience" field.
func AudienceNEQ(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNEQ(FieldAudience, v))
}

// AudienceIn applies the In predicate on the "audience" field.
func AudienceIn(vs ...string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldIn(FieldAudience, vs...))
}

// AudienceNotIn applies the NotIn predicate on the "audience" field.
func AudienceNotIn(vs ...string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNotIn(FieldAudience, vs...))
}

// AudienceGT applies the GT predicate on the "audience" field.
func AudienceGT(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGT(FieldAudience, v))
}

// AudienceGTE applies the GTE predicate on the "audience" field.
func AudienceGTE(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGTE(FieldAudience, v))
}

// AudienceLT applies the LT predicate on the "audience" field.
func AudienceLT(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLT(FieldAudience, v))
}

// AudienceLTE applies the LTE predicate on the "audience" field.
func AudienceLTE(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLTE(FieldAudience, v))
}

// AudienceContains applies the Contains predicate on the "audience" field.
func AudienceContains(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldContains(FieldAudience, v))
}

// AudienceHasPrefix applies the HasPrefix predicate on the "audience" field.
func AudienceHasPrefix(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldHasPrefix(FieldAudience, v))
}

// AudienceHasSuffix applies the HasSuffix predicate on the "audience" field.
func AudienceHasSuffix(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldHasSuffix(FieldAudience, v))
}

// AudienceEqualFold applies the EqualFold predicate on the "audience" field.
func AudienceEqualFold(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEqualFold(FieldAudience, v))
}

// AudienceContainsFold applies the ContainsFold predicate on the "audience" field.
func AudienceContainsFold(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldContainsFold(FieldAudience, v))
}

// ReadOnlyEQ applies the EQ predicate on the "read_only" field.
func ReadOnlyEQ(v bool) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldReadOnly, v))
}

// ReadOnlyNEQ applies the NEQ predicate on the "read_only" field.
func ReadOnlyNEQ(v bool) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNEQ(FieldReadOnly, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldContainsFold(FieldReason, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v int8) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v int8) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...int8) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...int8) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v int8) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v int8) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v int8) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v int8) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLTE(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLTE(FieldCreatedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLTE(FieldExpiresAt, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.FieldNotNull(FieldRevokedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ImpersonationSession) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ImpersonationSession) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ImpersonationSession) predicate.ImpersonationSession {
	return predicate.ImpersonationSession(sql.NotPredicates(p))
}
