// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// KprAppColumns holds the columns for the "kpr_app" table.
	KprAppColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeInt8, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// KprAppTable holds the schema information for the "kpr_app" table.
	KprAppTable = &schema.Table{
		Name:       "kpr_app",
		Columns:    KprAppColumns,
		PrimaryKey: []*schema.Column{KprAppColumns[0]},
	}
	// KprUserColumns holds the columns for the "kpr_user" table.
	KprUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "firstname", Type: field.TypeString},
		{Name: "lastname", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "status", Type: field.TypeInt8, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "app_id", Type: field.TypeInt},
	}
	// KprUserTable holds the schema information for the "kpr_user" table.
	KprUserTable = &schema.Table{
		Name:       "kpr_user",
		Columns:    KprUserColumns,
		PrimaryKey: []*schema.Column{KprUserColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "kpr_user_kpr_app_users",
				Columns:    []*schema.Column{KprUserColumns[8]},
				RefColumns: []*schema.Column{KprAppColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		KprAppTable,
		KprUserTable,
	}
)

func init() {
	KprAppTable.Annotation = &entsql.Annotation{
		Table: "kpr_app",
	}
	KprUserTable.ForeignKeys[0].RefTable = KprAppTable
	KprUserTable.Annotation = &entsql.Annotation{
		Table: "kpr_user",
	}
}
