// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// KprAppColumns holds the columns for the "kpr_app" table.
	KprAppColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "tagline", Type: field.TypeString, Nullable: true},
		{Name: "logo_url", Type: field.TypeString, Nullable: true},
		{Name: "about_heading", Type: field.TypeString, Nullable: true},
		{Name: "about_body", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "contact_address_line1", Type: field.TypeString, Nullable: true},
		{Name: "contact_address_line2", Type: field.TypeString, Nullable: true},
		{Name: "contact_city", Type: field.TypeString, Nullable: true},
		{Name: "contact_state", Type: field.TypeString, Nullable: true},
		{Name: "contact_country", Type: field.TypeString, Nullable: true},
		{Name: "contact_postal_code", Type: field.TypeString, Nullable: true},
		{Name: "contact_phone1", Type: field.TypeString, Nullable: true},
		{Name: "contact_phone2", Type: field.TypeString, Nullable: true},
		{Name: "contact_email", Type: field.TypeString, Nullable: true},
		{Name: "contact_hours", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "contact_social", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeInt8, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// KprAppTable holds the schema information for the "kpr_app" table.
	KprAppTable = &schema.Table{
		Name:       "kpr_app",
		Columns:    KprAppColumns,
		PrimaryKey: []*schema.Column{KprAppColumns[0]},
	}
	// KprDivisionColumns holds the columns for the "kpr_division" table.
	KprDivisionColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "depth", Type: field.TypeInt8, Default: 0},
		{Name: "status", Type: field.TypeInt8, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "app_id", Type: field.TypeInt},
		{Name: "parent_id", Type: field.TypeInt, Nullable: true},
	}
	// KprDivisionTable holds the schema information for the "kpr_division" table.
	KprDivisionTable = &schema.Table{
		Name:       "kpr_division",
		Columns:    KprDivisionColumns,
		PrimaryKey: []*schema.Column{KprDivisionColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "kpr_division_kpr_app_divisions",
				Columns:    []*schema.Column{KprDivisionColumns[7]},
				RefColumns: []*schema.Column{KprAppColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "kpr_division_kpr_division_children",
				Columns:    []*schema.Column{KprDivisionColumns[8]},
				RefColumns: []*schema.Column{KprDivisionColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "division_path",
				Unique:  false,
				Columns: []*schema.Column{KprDivisionColumns[2]},
			},
			{
				Name:    "division_app_id_parent_id",
				Unique:  false,
				Columns: []*schema.Column{KprDivisionColumns[7], KprDivisionColumns[8]},
			},
		},
	}
	// KprGuestKeyColumns holds the columns for the "kpr_guest_key" table.
	KprGuestKeyColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "app_id", Type: field.TypeInt},
		{Name: "division_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "site_key", Type: field.TypeString, Unique: true},
		{Name: "domain", Type: field.TypeString, Unique: true},
		{Name: "status", Type: field.TypeInt8, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// KprGuestKeyTable holds the schema information for the "kpr_guest_key" table.
	KprGuestKeyTable = &schema.Table{
		Name:       "kpr_guest_key",
		Columns:    KprGuestKeyColumns,
		PrimaryKey: []*schema.Column{KprGuestKeyColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "guestkey_app_id",
				Unique:  false,
				Columns: []*schema.Column{KprGuestKeyColumns[1]},
			},
		},
	}
	// KprUserColumns holds the columns for the "kpr_user" table.
	KprUserColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "firstname", Type: field.TypeString},
		{Name: "lastname", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "role", Type: field.TypeInt8, Default: 0},
		{Name: "status", Type: field.TypeInt8, Default: 1},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "app_id", Type: field.TypeInt},
		{Name: "division_id", Type: field.TypeInt},
	}
	// KprUserTable holds the schema information for the "kpr_user" table.
	KprUserTable = &schema.Table{
		Name:       "kpr_user",
		Columns:    KprUserColumns,
		PrimaryKey: []*schema.Column{KprUserColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "kpr_user_kpr_app_users",
				Columns:    []*schema.Column{KprUserColumns[9]},
				RefColumns: []*schema.Column{KprAppColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "kpr_user_kpr_division_users",
				Columns:    []*schema.Column{KprUserColumns[10]},
				RefColumns: []*schema.Column{KprDivisionColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "user_app_id",
				Unique:  false,
				Columns: []*schema.Column{KprUserColumns[9]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		KprAppTable,
		KprDivisionTable,
		KprGuestKeyTable,
		KprUserTable,
	}
)

func init() {
	KprAppTable.Annotation = &entsql.Annotation{
		Table: "kpr_app",
	}
	KprDivisionTable.ForeignKeys[0].RefTable = KprAppTable
	KprDivisionTable.ForeignKeys[1].RefTable = KprDivisionTable
	KprDivisionTable.Annotation = &entsql.Annotation{
		Table: "kpr_division",
	}
	KprGuestKeyTable.Annotation = &entsql.Annotation{
		Table: "kpr_guest_key",
	}
	KprUserTable.ForeignKeys[0].RefTable = KprAppTable
	KprUserTable.ForeignKeys[1].RefTable = KprDivisionTable
	KprUserTable.Annotation = &entsql.Annotation{
		Table: "kpr_user",
	}
}
