// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"keeper/ent/app"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// App is the model entity for the App schema.
type App struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Tagline holds the value of the "tagline" field.
	Tagline string `json:"tagline,omitempty"`
	// LogoURL holds the value of the "logo_url" field.
	LogoURL string `json:"logo_url,omitempty"`
	// AboutHeading holds the value of the "about_heading" field.
	AboutHeading string `json:"about_heading,omitempty"`
	// AboutBody holds the value of the "about_body" field.
	AboutBody string `json:"about_body,omitempty"`
	// ContactAddressLine1 holds the value of the "contact_address_line1" field.
	ContactAddressLine1 string `json:"contact_address_line1,omitempty"`
	// ContactAddressLine2 holds the value of the "contact_address_line2" field.
	ContactAddressLine2 string `json:"contact_address_line2,omitempty"`
	// ContactCity holds the value of the "contact_city" field.
	ContactCity string `json:"contact_city,omitempty"`
	// ContactState holds the value of the "contact_state" field.
	ContactState string `json:"contact_state,omitempty"`
	// ContactCountry holds the value of the "contact_country" field.
	ContactCountry string `json:"contact_country,omitempty"`
	// ContactPostalCode holds the value of the "contact_postal_code" field.
	ContactPostalCode string `json:"contact_postal_code,omitempty"`
	// ContactPhone1 holds the value of the "contact_phone1" field.
	ContactPhone1 string `json:"contact_phone1,omitempty"`
	// ContactPhone2 holds the value of the "contact_phone2" field.
	ContactPhone2 string `json:"contact_phone2,omitempty"`
	// ContactEmail holds the value of the "contact_email" field.
	ContactEmail string `json:"contact_email,omitempty"`
	// ContactHours holds the value of the "contact_hours" field.
	ContactHours string `json:"contact_hours,omitempty"`
	// ContactSocial holds the value of the "contact_social" field.
	ContactSocial map[string]string `json:"contact_social,omitempty"`
	// TaxNumber holds the value of the "tax_number" field.
	TaxNumber string `json:"tax_number,omitempty"`
	// TaxPercent holds the value of the "tax_percent" field.
	TaxPercent float64 `json:"tax_percent,omitempty"`
	// Status holds the value of the "status" field.
	Status int8 `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AppQuery when eager-loading is set.
	Edges        AppEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AppEdges holds the relations/edges for other nodes in the graph.
type AppEdges struct {
	// Users holds the value of the users edge.
	Users []*User `json:"users,omitempty"`
	// Divisions holds the value of the divisions edge.
	Divisions []*Division `json:"divisions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading.
func (e AppEdges) UsersOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// DivisionsOrErr returns the Divisions value or an error if the edge
// was not loaded in eager-loading.
func (e AppEdges) DivisionsOrErr() ([]*Division, error) {
	if e.loadedTypes[1] {
		return e.Divisions, nil
	}
	return nil, &NotLoadedError{edge: "divisions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*App) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case app.FieldContactSocial:
			values[i] = new([]byte)
		case app.FieldTaxPercent:
			values[i] = new(sql.NullFloat64)
		case app.FieldID, app.FieldStatus:
			values[i] = new(sql.NullInt64)
		case app.FieldName, app.FieldTagline, app.FieldLogoURL, app.FieldAboutHeading, app.FieldAboutBody, app.FieldContactAddressLine1, app.FieldContactAddressLine2, app.FieldContactCity, app.FieldContactState, app.FieldContactCountry, app.FieldContactPostalCode, app.FieldContactPhone1, app.FieldContactPhone2, app.FieldContactEmail, app.FieldContactHours, app.FieldTaxNumber:
			values[i] = new(sql.NullString)
		case app.FieldCreatedAt, app.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the App fields.
func (_m *App) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case app.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case app.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case app.FieldTagline:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tagline", values[i])
			} else if value.Valid {
				_m.Tagline = value.String
			}
		case app.FieldLogoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logo_url", values[i])
			} else if value.Valid {
				_m.LogoURL = value.String
			}
		case app.FieldAboutHeading:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field about_heading", values[i])
			} else if value.Valid {
				_m.AboutHeading = value.String
			}
		case app.FieldAboutBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field about_body", values[i])
			} else if value.Valid {
				_m.AboutBody = value.String
			}
		case app.FieldContactAddressLine1:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_address_line1", values[i])
			} else if value.Valid {
				_m.ContactAddressLine1 = value.String
			}
		case app.FieldContactAddressLine2:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_address_line2", values[i])
			} else if value.Valid {
				_m.ContactAddressLine2 = value.String
			}
		case app.FieldContactCity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_city", values[i])
			} else if value.Valid {
				_m.ContactCity = value.String
			}
		case app.FieldContactState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_state", values[i])
			} else if value.Valid {
				_m.ContactState = value.String
			}
		case app.FieldContactCountry:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_country", values[i])
			} else if value.Valid {
				_m.ContactCountry = value.String
			}
		case app.FieldContactPostalCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_postal_code", values[i])
			} else if value.Valid {
				_m.ContactPostalCode = value.String
			}
		case app.FieldContactPhone1:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_phone1", values[i])
			} else if value.Valid {
				_m.ContactPhone1 = value.String
			}
		case app.FieldContactPhone2:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_phone2", values[i])
			} else if value.Valid {
				_m.ContactPhone2 = value.String
			}
		case app.FieldContactEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_email", values[i])
			} else if value.Valid {
				_m.ContactEmail = value.String
			}
		case app.FieldContactHours:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_hours", values[i])
			} else if value.Valid {
				_m.ContactHours = value.String
			}
		case app.FieldContactSocial:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field contact_social", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ContactSocial); err != nil {
					return fmt.Errorf("unmarshal field contact_social: %w", err)
				}
			}
		case app.FieldTaxNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_number", values[i])
			} else if value.Valid {
				_m.TaxNumber = value.String
			}
		case app.FieldTaxPercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field tax_percent", values[i])
			} else if value.Valid {
				_m.TaxPercent = value.Float64
			}
		case app.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int8(value.Int64)
			}
		case app.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case app.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the App.
// This includes values selected through modifiers, order, etc.
func (_m *App) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsers queries the "users" edge of the App entity.
func (_m *App) QueryUsers() *UserQuery {
	return NewAppClient(_m.config).QueryUsers(_m)
}

// QueryDivisions queries the "divisions" edge of the App entity.
func (_m *App) QueryDivisions() *DivisionQuery {
	return NewAppClient(_m.config).QueryDivisions(_m)
}

// Update returns a builder for updating this App.
// Note that you need to call App.Unwrap() before calling this method if this App
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *App) Update() *AppUpdateOne {
	return NewAppClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the App entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *App) Unwrap() *App {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: App is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *App) String() string {
	var builder strings.Builder
	builder.WriteString("App(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("tagline=")
	builder.WriteString(_m.Tagline)
	builder.WriteString(", ")
	builder.WriteString("logo_url=")
	builder.WriteString(_m.LogoURL)
	builder.WriteString(", ")
	builder.WriteString("about_heading=")
	builder.WriteString(_m.AboutHeading)
	builder.WriteString(", ")
	builder.WriteString("about_body=")
	builder.WriteString(_m.AboutBody)
	builder.WriteString(", ")
	builder.WriteString("contact_address_line1=")
	builder.WriteString(_m.ContactAddressLine1)
	builder.WriteString(", ")
	builder.WriteString("contact_address_line2=")
	builder.WriteString(_m.ContactAddressLine2)
	builder.WriteString(", ")
	builder.WriteString("contact_city=")
	builder.WriteString(_m.ContactCity)
	builder.WriteString(", ")
	builder.WriteString("contact_state=")
	builder.WriteString(_m.ContactState)
	builder.WriteString(", ")
	builder.WriteString("contact_country=")
	builder.WriteString(_m.ContactCountry)
	builder.WriteString(", ")
	builder.WriteString("contact_postal_code=")
	builder.WriteString(_m.ContactPostalCode)
	builder.WriteString(", ")
	builder.WriteString("contact_phone1=")
	builder.WriteString(_m.ContactPhone1)
	builder.WriteString(", ")
	builder.WriteString("contact_phone2=")
	builder.WriteString(_m.ContactPhone2)
	builder.WriteString(", ")
	builder.WriteString("contact_email=")
	builder.WriteString(_m.ContactEmail)
	builder.WriteString(", ")
	builder.WriteString("contact_hours=")
	builder.WriteString(_m.ContactHours)
	builder.WriteString(", ")
	builder.WriteString("contact_social=")
	builder.WriteString(fmt.Sprintf("%v", _m.ContactSocial))
	builder.WriteString(", ")
	builder.WriteString("tax_number=")
	builder.WriteString(_m.TaxNumber)
	builder.WriteString(", ")
	builder.WriteString("tax_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaxPercent))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Apps is a parsable slice of App.
type Apps []*App
