// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"keeper/ent/app"
	"keeper/ent/division"
	"keeper/ent/predicate"
	"keeper/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DivisionUpdate is the builder for updating Division entities.
type DivisionUpdate struct {
	config
	hooks    []Hook
	mutation *DivisionMutation
}

// Where appends a list predicates to the DivisionUpdate builder.
func (_u *DivisionUpdate) Where(ps ...predicate.Division) *DivisionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *DivisionUpdate) SetAppID(v int) *DivisionUpdate {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *DivisionUpdate) SetNillableAppID(v *int) *DivisionUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *DivisionUpdate) SetParentID(v int) *DivisionUpdate {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *DivisionUpdate) SetNillableParentID(v *int) *DivisionUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *DivisionUpdate) ClearParentID() *DivisionUpdate {
	_u.mutation.ClearParentID()
	return _u
}

// SetName sets the "name" field.
func (_u *DivisionUpdate) SetName(v string) *DivisionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DivisionUpdate) SetNillableName(v *string) *DivisionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *DivisionUpdate) SetPath(v string) *DivisionUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *DivisionUpdate) SetNillablePath(v *string) *DivisionUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetDepth sets the "depth" field.
func (_u *DivisionUpdate) SetDepth(v int8) *DivisionUpdate {
	_u.mutation.ResetDepth()
	_u.mutation.SetDepth(v)
	return _u
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (_u *DivisionUpdate) SetNillableDepth(v *int8) *DivisionUpdate {
	if v != nil {
		_u.SetDepth(*v)
	}
	return _u
}

// AddDepth adds value to the "depth" field.
func (_u *DivisionUpdate) AddDepth(v int8) *DivisionUpdate {
	_u.mutation.AddDepth(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DivisionUpdate) SetStatus(v int8) *DivisionUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DivisionUpdate) SetNillableStatus(v *int8) *DivisionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *DivisionUpdate) AddStatus(v int8) *DivisionUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DivisionUpdate) SetCreatedAt(v time.Time) *DivisionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DivisionUpdate) SetNillableCreatedAt(v *time.Time) *DivisionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DivisionUpdate) SetUpdatedAt(v time.Time) *DivisionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddChildIDs adds the "children" edge to the Division entity by IDs.
func (_u *DivisionUpdate) AddChildIDs(ids ...int) *DivisionUpdate {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Division entity.
func (_u *DivisionUpdate) AddChildren(v ...*Division) *DivisionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// SetParent sets the "parent" edge to the Division entity.
func (_u *DivisionUpdate) SetParent(v *Division) *DivisionUpdate {
	return _u.SetParentID(v.ID)
}

// SetApp sets the "app" edge to the App entity.
func (_u *DivisionUpdate) SetApp(v *App) *DivisionUpdate {
	return _u.SetAppID(v.ID)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *DivisionUpdate) AddUserIDs(ids ...int) *DivisionUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *DivisionUpdate) AddUsers(v ...*User) *DivisionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the DivisionMutation object of the builder.
func (_u *DivisionUpdate) Mutation() *DivisionMutation {
	return _u.mutation
}

// ClearChildren clears all "children" edges to the Division entity.
func (_u *DivisionUpdate) ClearChildren() *DivisionUpdate {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Division entities by IDs.
func (_u *DivisionUpdate) RemoveChildIDs(ids ...int) *DivisionUpdate {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Division entities.
func (_u *DivisionUpdate) RemoveChildren(v ...*Division) *DivisionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearParent clears the "parent" edge to the Division entity.
func (_u *DivisionUpdate) ClearParent() *DivisionUpdate {
	_u.mutation.ClearParent()
	return _u
}

// ClearApp clears the "app" edge to the App entity.
func (_u *DivisionUpdate) ClearApp() *DivisionUpdate {
	_u.mutation.ClearApp()
	return _u
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *DivisionUpdate) ClearUsers() *DivisionUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *DivisionUpdate) RemoveUserIDs(ids ...int) *DivisionUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *DivisionUpdate) RemoveUsers(v ...*User) *DivisionUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DivisionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DivisionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DivisionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DivisionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DivisionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := division.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DivisionUpdate) check() error {
	if _u.mutation.AppCleared() && len(_u.mutation.AppIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Division.app"`)
	}
	return nil
}

func (_u *DivisionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(division.Table, division.Columns, sqlgraph.NewFieldSpec(division.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(division.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(division.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Depth(); ok {
		_spec.SetField(division.FieldDepth, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedDepth(); ok {
		_spec.AddField(division.FieldDepth, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(division.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(division.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(division.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(division.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   division.ChildrenTable,
			Columns: []string{division.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(division.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   division.ChildrenTable,
			Columns: []string{division.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(division.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   division.ChildrenTable,
			Columns: []string{division.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(division.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   division.ParentTable,
			Columns: []string{division.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(division.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   division.ParentTable,
			Columns: []string{division.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(division.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   division.AppTable,
			Columns: []string{division.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   division.AppTable,
			Columns: []string{division.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   division.UsersTable,
			Columns: []string{division.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   division.UsersTable,
			Columns: []string{division.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   division.UsersTable,
			Columns: []string{division.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{division.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DivisionUpdateOne is the builder for updating a single Division entity.
type DivisionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DivisionMutation
}

// SetAppID sets the "app_id" field.
func (_u *DivisionUpdateOne) SetAppID(v int) *DivisionUpdateOne {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *DivisionUpdateOne) SetNillableAppID(v *int) *DivisionUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *DivisionUpdateOne) SetParentID(v int) *DivisionUpdateOne {
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *DivisionUpdateOne) SetNillableParentID(v *int) *DivisionUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// ClearParentID clears the value of the "parent_id" field.
func (_u *DivisionUpdateOne) ClearParentID() *DivisionUpdateOne {
	_u.mutation.ClearParentID()
	return _u
}

// SetName sets the "name" field.
func (_u *DivisionUpdateOne) SetName(v string) *DivisionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *DivisionUpdateOne) SetNillableName(v *string) *DivisionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *DivisionUpdateOne) SetPath(v string) *DivisionUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *DivisionUpdateOne) SetNillablePath(v *string) *DivisionUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetDepth sets the "depth" field.
func (_u *DivisionUpdateOne) SetDepth(v int8) *DivisionUpdateOne {
	_u.mutation.ResetDepth()
	_u.mutation.SetDepth(v)
	return _u
}

// SetNillableDepth sets the "depth" field if the given value is not nil.
func (_u *DivisionUpdateOne) SetNillableDepth(v *int8) *DivisionUpdateOne {
	if v != nil {
		_u.SetDepth(*v)
	}
	return _u
}

// AddDepth adds value to the "depth" field.
func (_u *DivisionUpdateOne) AddDepth(v int8) *DivisionUpdateOne {
	_u.mutation.AddDepth(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DivisionUpdateOne) SetStatus(v int8) *DivisionUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DivisionUpdateOne) SetNillableStatus(v *int8) *DivisionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *DivisionUpdateOne) AddStatus(v int8) *DivisionUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DivisionUpdateOne) SetCreatedAt(v time.Time) *DivisionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DivisionUpdateOne) SetNillableCreatedAt(v *time.Time) *DivisionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DivisionUpdateOne) SetUpdatedAt(v time.Time) *DivisionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddChildIDs adds the "children" edge to the Division entity by IDs.
func (_u *DivisionUpdateOne) AddChildIDs(ids ...int) *DivisionUpdateOne {
	_u.mutation.AddChildIDs(ids...)
	return _u
}

// AddChildren adds the "children" edges to the Division entity.
func (_u *DivisionUpdateOne) AddChildren(v ...*Division) *DivisionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChildIDs(ids...)
}

// SetParent sets the "parent" edge to the Division entity.
func (_u *DivisionUpdateOne) SetParent(v *Division) *DivisionUpdateOne {
	return _u.SetParentID(v.ID)
}

// SetApp sets the "app" edge to the App entity.
func (_u *DivisionUpdateOne) SetApp(v *App) *DivisionUpdateOne {
	return _u.SetAppID(v.ID)
}

// AddUserIDs adds the "users" edge to the User entity by IDs.
func (_u *DivisionUpdateOne) AddUserIDs(ids ...int) *DivisionUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUsers adds the "users" edges to the User entity.
func (_u *DivisionUpdateOne) AddUsers(v ...*User) *DivisionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the DivisionMutation object of the builder.
func (_u *DivisionUpdateOne) Mutation() *DivisionMutation {
	return _u.mutation
}

// ClearChildren clears all "children" edges to the Division entity.
func (_u *DivisionUpdateOne) ClearChildren() *DivisionUpdateOne {
	_u.mutation.ClearChildren()
	return _u
}

// RemoveChildIDs removes the "children" edge to Division entities by IDs.
func (_u *DivisionUpdateOne) RemoveChildIDs(ids ...int) *DivisionUpdateOne {
	_u.mutation.RemoveChildIDs(ids...)
	return _u
}

// RemoveChildren removes "children" edges to Division entities.
func (_u *DivisionUpdateOne) RemoveChildren(v ...*Division) *DivisionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChildIDs(ids...)
}

// ClearParent clears the "parent" edge to the Division entity.
func (_u *DivisionUpdateOne) ClearParent() *DivisionUpdateOne {
	_u.mutation.ClearParent()
	return _u
}

// ClearApp clears the "app" edge to the App entity.
func (_u *DivisionUpdateOne) ClearApp() *DivisionUpdateOne {
	_u.mutation.ClearApp()
	return _u
}

// ClearUsers clears all "users" edges to the User entity.
func (_u *DivisionUpdateOne) ClearUsers() *DivisionUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// RemoveUserIDs removes the "users" edge to User entities by IDs.
func (_u *DivisionUpdateOne) RemoveUserIDs(ids ...int) *DivisionUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUsers removes "users" edges to User entities.
func (_u *DivisionUpdateOne) RemoveUsers(v ...*User) *DivisionUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Where appends a list predicates to the DivisionUpdate builder.
func (_u *DivisionUpdateOne) Where(ps ...predicate.Division) *DivisionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DivisionUpdateOne) Select(field string, fields ...string) *DivisionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Division entity.
func (_u *DivisionUpdateOne) Save(ctx context.Context) (*Division, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DivisionUpdateOne) SaveX(ctx context.Context) *Division {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DivisionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DivisionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DivisionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := division.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DivisionUpdateOne) check() error {
	if _u.mutation.AppCleared() && len(_u.mutation.AppIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Division.app"`)
	}
	return nil
}

func (_u *DivisionUpdateOne) sqlSave(ctx context.Context) (_node *Division, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(division.Table, division.Columns, sqlgraph.NewFieldSpec(division.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Division.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, division.FieldID)
		for _, f := range fields {
			if !division.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != division.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(division.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(division.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Depth(); ok {
		_spec.SetField(division.FieldDepth, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedDepth(); ok {
		_spec.AddField(division.FieldDepth, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(division.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(division.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(division.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(division.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   division.ChildrenTable,
			Columns: []string{division.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(division.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !_u.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   division.ChildrenTable,
			Columns: []string{division.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(division.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   division.ChildrenTable,
			Columns: []string{division.ChildrenColumn},
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(division.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   division.ParentTable,
			Columns: []string{division.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(division.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   division.ParentTable,
			Columns: []string{division.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(division.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   division.AppTable,
			Columns: []string{division.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   division.AppTable,
			Columns: []string{division.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   division.UsersTable,
			Columns: []string{division.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsersIDs(); len(nodes) > 0 && !_u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   division.UsersTable,
			Columns: []string{division.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   division.UsersTable,
			Columns: []string{division.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Division{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{division.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
