// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"keeper/ent/guestkey"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GuestKeyCreate is the builder for creating a GuestKey entity.
type GuestKeyCreate struct {
	config
	mutation *GuestKeyMutation
	hooks    []Hook
}

// SetAppID sets the "app_id" field.
func (_c *GuestKeyCreate) SetAppID(v int) *GuestKeyCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetDivisionID sets the "division_id" field.
func (_c *GuestKeyCreate) SetDivisionID(v int) *GuestKeyCreate {
	_c.mutation.SetDivisionID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *GuestKeyCreate) SetUserID(v int) *GuestKeyCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *GuestKeyCreate) SetName(v string) *GuestKeyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSiteKey sets the "site_key" field.
func (_c *GuestKeyCreate) SetSiteKey(v string) *GuestKeyCreate {
	_c.mutation.SetSiteKey(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *GuestKeyCreate) SetStatus(v int8) *GuestKeyCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *GuestKeyCreate) SetNillableStatus(v *int8) *GuestKeyCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GuestKeyCreate) SetCreatedAt(v time.Time) *GuestKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GuestKeyCreate) SetNillableCreatedAt(v *time.Time) *GuestKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GuestKeyCreate) SetUpdatedAt(v time.Time) *GuestKeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GuestKeyCreate) SetNillableUpdatedAt(v *time.Time) *GuestKeyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the GuestKeyMutation object of the builder.
func (_c *GuestKeyCreate) Mutation() *GuestKeyMutation {
	return _c.mutation
}

// Save creates the GuestKey in the database.
func (_c *GuestKeyCreate) Save(ctx context.Context) (*GuestKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GuestKeyCreate) SaveX(ctx context.Context) *GuestKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GuestKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GuestKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GuestKeyCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := guestkey.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := guestkey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := guestkey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GuestKeyCreate) check() error {
	if _, ok := _c.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "GuestKey.app_id"`)}
	}
	if _, ok := _c.mutation.DivisionID(); !ok {
		return &ValidationError{Name: "division_id", err: errors.New(`ent: missing required field "GuestKey.division_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "GuestKey.user_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "GuestKey.name"`)}
	}
	if _, ok := _c.mutation.SiteKey(); !ok {
		return &ValidationError{Name: "site_key", err: errors.New(`ent: missing required field "GuestKey.site_key"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "GuestKey.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GuestKey.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GuestKey.updated_at"`)}
	}
	return nil
}

func (_c *GuestKeyCreate) sqlSave(ctx context.Context) (*GuestKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GuestKeyCreate) createSpec() (*GuestKey, *sqlgraph.CreateSpec) {
	var (
		_node = &GuestKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(guestkey.Table, sqlgraph.NewFieldSpec(guestkey.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.AppID(); ok {
		_spec.SetField(guestkey.FieldAppID, field.TypeInt, value)
		_node.AppID = value
	}
	if value, ok := _c.mutation.DivisionID(); ok {
		_spec.SetField(guestkey.FieldDivisionID, field.TypeInt, value)
		_node.DivisionID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(guestkey.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(guestkey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.SiteKey(); ok {
		_spec.SetField(guestkey.FieldSiteKey, field.TypeString, value)
		_node.SiteKey = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(guestkey.FieldStatus, field.TypeInt8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(guestkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(guestkey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// GuestKeyCreateBulk is the builder for creating many GuestKey entities in bulk.
type GuestKeyCreateBulk struct {
	config
	err      error
	builders []*GuestKeyCreate
}

// Save creates the GuestKey entities in the database.
func (_c *GuestKeyCreateBulk) Save(ctx context.Context) ([]*GuestKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GuestKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GuestKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GuestKeyCreateBulk) SaveX(ctx context.Context) []*GuestKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GuestKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GuestKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
