// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"keeper/ent/guestkey"
	"keeper/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GuestKeyUpdate is the builder for updating GuestKey entities.
type GuestKeyUpdate struct {
	config
	hooks    []Hook
	mutation *GuestKeyMutation
}

// Where appends a list predicates to the GuestKeyUpdate builder.
func (_u *GuestKeyUpdate) Where(ps ...predicate.GuestKey) *GuestKeyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *GuestKeyUpdate) SetAppID(v int) *GuestKeyUpdate {
	_u.mutation.ResetAppID()
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *GuestKeyUpdate) SetNillableAppID(v *int) *GuestKeyUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// AddAppID adds value to the "app_id" field.
func (_u *GuestKeyUpdate) AddAppID(v int) *GuestKeyUpdate {
	_u.mutation.AddAppID(v)
	return _u
}

// SetDivisionID sets the "division_id" field.
func (_u *GuestKeyUpdate) SetDivisionID(v int) *GuestKeyUpdate {
	_u.mutation.ResetDivisionID()
	_u.mutation.SetDivisionID(v)
	return _u
}

// SetNillableDivisionID sets the "division_id" field if the given value is not nil.
func (_u *GuestKeyUpdate) SetNillableDivisionID(v *int) *GuestKeyUpdate {
	if v != nil {
		_u.SetDivisionID(*v)
	}
	return _u
}

// AddDivisionID adds value to the "division_id" field.
func (_u *GuestKeyUpdate) AddDivisionID(v int) *GuestKeyUpdate {
	_u.mutation.AddDivisionID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GuestKeyUpdate) SetUserID(v int) *GuestKeyUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GuestKeyUpdate) SetNillableUserID(v *int) *GuestKeyUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *GuestKeyUpdate) AddUserID(v int) *GuestKeyUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *GuestKeyUpdate) SetName(v string) *GuestKeyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GuestKeyUpdate) SetNillableName(v *string) *GuestKeyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSiteKey sets the "site_key" field.
func (_u *GuestKeyUpdate) SetSiteKey(v string) *GuestKeyUpdate {
	_u.mutation.SetSiteKey(v)
	return _u
}

// SetNillableSiteKey sets the "site_key" field if the given value is not nil.
func (_u *GuestKeyUpdate) SetNillableSiteKey(v *string) *GuestKeyUpdate {
	if v != nil {
		_u.SetSiteKey(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *GuestKeyUpdate) SetDomain(v string) *GuestKeyUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *GuestKeyUpdate) SetNillableDomain(v *string) *GuestKeyUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GuestKeyUpdate) SetStatus(v int8) *GuestKeyUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GuestKeyUpdate) SetNillableStatus(v *int8) *GuestKeyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *GuestKeyUpdate) AddStatus(v int8) *GuestKeyUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GuestKeyUpdate) SetCreatedAt(v time.Time) *GuestKeyUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GuestKeyUpdate) SetNillableCreatedAt(v *time.Time) *GuestKeyUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GuestKeyUpdate) SetUpdatedAt(v time.Time) *GuestKeyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GuestKeyMutation object of the builder.
func (_u *GuestKeyUpdate) Mutation() *GuestKeyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GuestKeyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GuestKeyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GuestKeyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GuestKeyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GuestKeyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := guestkey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *GuestKeyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(guestkey.Table, guestkey.Columns, sqlgraph.NewFieldSpec(guestkey.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(guestkey.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAppID(); ok {
		_spec.AddField(guestkey.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DivisionID(); ok {
		_spec.SetField(guestkey.FieldDivisionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDivisionID(); ok {
		_spec.AddField(guestkey.FieldDivisionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(guestkey.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(guestkey.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(guestkey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SiteKey(); ok {
		_spec.SetField(guestkey.FieldSiteKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(guestkey.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(guestkey.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(guestkey.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(guestkey.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(guestkey.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{guestkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GuestKeyUpdateOne is the builder for updating a single GuestKey entity.
type GuestKeyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GuestKeyMutation
}

// SetAppID sets the "app_id" field.
func (_u *GuestKeyUpdateOne) SetAppID(v int) *GuestKeyUpdateOne {
	_u.mutation.ResetAppID()
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *GuestKeyUpdateOne) SetNillableAppID(v *int) *GuestKeyUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// AddAppID adds value to the "app_id" field.
func (_u *GuestKeyUpdateOne) AddAppID(v int) *GuestKeyUpdateOne {
	_u.mutation.AddAppID(v)
	return _u
}

// SetDivisionID sets the "division_id" field.
func (_u *GuestKeyUpdateOne) SetDivisionID(v int) *GuestKeyUpdateOne {
	_u.mutation.ResetDivisionID()
	_u.mutation.SetDivisionID(v)
	return _u
}

// SetNillableDivisionID sets the "division_id" field if the given value is not nil.
func (_u *GuestKeyUpdateOne) SetNillableDivisionID(v *int) *GuestKeyUpdateOne {
	if v != nil {
		_u.SetDivisionID(*v)
	}
	return _u
}

// AddDivisionID adds value to the "division_id" field.
func (_u *GuestKeyUpdateOne) AddDivisionID(v int) *GuestKeyUpdateOne {
	_u.mutation.AddDivisionID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GuestKeyUpdateOne) SetUserID(v int) *GuestKeyUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GuestKeyUpdateOne) SetNillableUserID(v *int) *GuestKeyUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *GuestKeyUpdateOne) AddUserID(v int) *GuestKeyUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetName sets the "name" field.
func (_u *GuestKeyUpdateOne) SetName(v string) *GuestKeyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *GuestKeyUpdateOne) SetNillableName(v *string) *GuestKeyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSiteKey sets the "site_key" field.
func (_u *GuestKeyUpdateOne) SetSiteKey(v string) *GuestKeyUpdateOne {
	_u.mutation.SetSiteKey(v)
	return _u
}

// SetNillableSiteKey sets the "site_key" field if the given value is not nil.
func (_u *GuestKeyUpdateOne) SetNillableSiteKey(v *string) *GuestKeyUpdateOne {
	if v != nil {
		_u.SetSiteKey(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *GuestKeyUpdateOne) SetDomain(v string) *GuestKeyUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *GuestKeyUpdateOne) SetNillableDomain(v *string) *GuestKeyUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *GuestKeyUpdateOne) SetStatus(v int8) *GuestKeyUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GuestKeyUpdateOne) SetNillableStatus(v *int8) *GuestKeyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *GuestKeyUpdateOne) AddStatus(v int8) *GuestKeyUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *GuestKeyUpdateOne) SetCreatedAt(v time.Time) *GuestKeyUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *GuestKeyUpdateOne) SetNillableCreatedAt(v *time.Time) *GuestKeyUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GuestKeyUpdateOne) SetUpdatedAt(v time.Time) *GuestKeyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GuestKeyMutation object of the builder.
func (_u *GuestKeyUpdateOne) Mutation() *GuestKeyMutation {
	return _u.mutation
}

// Where appends a list predicates to the GuestKeyUpdate builder.
func (_u *GuestKeyUpdateOne) Where(ps ...predicate.GuestKey) *GuestKeyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GuestKeyUpdateOne) Select(field string, fields ...string) *GuestKeyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GuestKey entity.
func (_u *GuestKeyUpdateOne) Save(ctx context.Context) (*GuestKey, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GuestKeyUpdateOne) SaveX(ctx context.Context) *GuestKey {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GuestKeyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GuestKeyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GuestKeyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := guestkey.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *GuestKeyUpdateOne) sqlSave(ctx context.Context) (_node *GuestKey, err error) {
	_spec := sqlgraph.NewUpdateSpec(guestkey.Table, guestkey.Columns, sqlgraph.NewFieldSpec(guestkey.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GuestKey.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, guestkey.FieldID)
		for _, f := range fields {
			if !guestkey.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != guestkey.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(guestkey.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAppID(); ok {
		_spec.AddField(guestkey.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DivisionID(); ok {
		_spec.SetField(guestkey.FieldDivisionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDivisionID(); ok {
		_spec.AddField(guestkey.FieldDivisionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(guestkey.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(guestkey.FieldUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(guestkey.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.SiteKey(); ok {
		_spec.SetField(guestkey.FieldSiteKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(guestkey.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(guestkey.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(guestkey.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(guestkey.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(guestkey.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &GuestKey{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{guestkey.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
