// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"keeper/ent/guestkey"
	"keeper/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GuestKeyDelete is the builder for deleting a GuestKey entity.
type GuestKeyDelete struct {
	config
	hooks    []Hook
	mutation *GuestKeyMutation
}

// Where appends a list predicates to the GuestKeyDelete builder.
func (_d *GuestKeyDelete) Where(ps ...predicate.GuestKey) *GuestKeyDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GuestKeyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GuestKeyDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GuestKeyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(guestkey.Table, sqlgraph.NewFieldSpec(guestkey.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GuestKeyDeleteOne is the builder for deleting a single GuestKey entity.
type GuestKeyDeleteOne struct {
	_d *GuestKeyDelete
}

// Where appends a list predicates to the GuestKeyDelete builder.
func (_d *GuestKeyDeleteOne) Where(ps ...predicate.GuestKey) *GuestKeyDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GuestKeyDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{guestkey.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GuestKeyDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
