// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"keeper/ent/impersonationsession"
	"keeper/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ImpersonationSessionUpdate is the builder for updating ImpersonationSession entities.
type ImpersonationSessionUpdate struct {
	config
	hooks    []Hook
	mutation *ImpersonationSessionMutation
}

// Where appends a list predicates to the ImpersonationSessionUpdate builder.
func (_u *ImpersonationSessionUpdate) Where(ps ...predicate.ImpersonationSession) *ImpersonationSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *ImpersonationSessionUpdate) SetSessionID(v string) *ImpersonationSessionUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *ImpersonationSessionUpdate) SetNillableSessionID(v *string) *ImpersonationSessionUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *ImpersonationSessionUpdate) SetAppID(v int) *ImpersonationSessionUpdate {
	_u.mutation.ResetAppID()
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *ImpersonationSessionUpdate) SetNillableAppID(v *int) *ImpersonationSessionUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// AddAppID adds value to the "app_id" field.
func (_u *ImpersonationSessionUpdate) AddAppID(v int) *ImpersonationSessionUpdate {
	_u.mutation.AddAppID(v)
	return _u
}

// SetDivisionID sets the "division_id" field.
func (_u *ImpersonationSessionUpdate) SetDivisionID(v int) *ImpersonationSessionUpdate {
	_u.mutation.ResetDivisionID()
	_u.mutation.SetDivisionID(v)
	return _u
}

// SetNillableDivisionID sets the "division_id" field if the given value is not nil.
func (_u *ImpersonationSessionUpdate) SetNillableDivisionID(v *int) *ImpersonationSessionUpdate {
	if v != nil {
		_u.SetDivisionID(*v)
	}
	return _u
}

// AddDivisionID adds value to the "division_id" field.
func (_u *ImpersonationSessionUpdate) AddDivisionID(v int) *ImpersonationSessionUpdate {
	_u.mutation.AddDivisionID(v)
	return _u
}

// SetImpersonatorUserID sets the "impersonator_user_id" field.
func (_u *ImpersonationSessionUpdate) SetImpersonatorUserID(v int) *ImpersonationSessionUpdate {
	_u.mutation.ResetImpersonatorUserID()
	_u.mutation.SetImpersonatorUserID(v)
	return _u
}

// SetNillableImpersonatorUserID sets the "impersonator_user_id" field if the given value is not nil.
func (_u *ImpersonationSessionUpdate) SetNillableImpersonatorUserID(v *int) *ImpersonationSessionUpdate {
	if v != nil {
		_u.SetImpersonatorUserID(*v)
	}
	return _u
}

// AddImpersonatorUserID adds value to the "impersonator_user_id" field.
func (_u *ImpersonationSessionUpdate) AddImpersonatorUserID(v int) *ImpersonationSessionUpdate {
	_u.mutation.AddImpersonatorUserID(v)
	return _u
}

// SetTargetUserID sets the "target_user_id" field.
func (_u *ImpersonationSessionUpdate) SetTargetUserID(v int) *ImpersonationSessionUpdate {
	_u.mutation.ResetTargetUserID()
	_u.mutation.SetTargetUserID(v)
	return _u
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (_u *ImpersonationSessionUpdate) SetNillableTargetUserID(v *int) *ImpersonationSessionUpdate {
	if v != nil {
		_u.SetTargetUserID(*v)
	}
	return _u
}

// AddTargetUserID adds value to the "target_user_id" field.
func (_u *ImpersonationSessionUpdate) AddTargetUserID(v int) *ImpersonationSessionUpdate {
	_u.mutation.AddTargetUserID(v)
	return _u
}

// SetAudience sets the "audience" field.
func (_u *ImpersonationSessionUpdate) SetAudience(v string) *ImpersonationSessionUpdate {
	_u.mutation.SetAudience(v)
	return _u
}

// SetNillableAudience sets the "audience" field if the given value is not nil.
func (_u *ImpersonationSessionUpdate) SetNillableAudience(v *string) *ImpersonationSessionUpdate {
	if v != nil {
		_u.SetAudience(*v)
	}
	return _u
}

// SetReadOnly sets the "read_only" field.
func (_u *ImpersonationSessionUpdate) SetReadOnly(v bool) *ImpersonationSessionUpdate {
	_u.mutation.SetReadOnly(v)
	return _u
}

// SetNillableReadOnly sets the "read_only" field if the given value is not nil.
func (_u *ImpersonationSessionUpdate) SetNillableReadOnly(v *bool) *ImpersonationSessionUpdate {
	if v != nil {
		_u.SetReadOnly(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *ImpersonationSessionUpdate) SetReason(v string) *ImpersonationSessionUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *ImpersonationSessionUpdate) SetNillableReason(v *string) *ImpersonationSessionUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *ImpersonationSessionUpdate) ClearReason() *ImpersonationSessionUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ImpersonationSessionUpdate) SetStatus(v int8) *ImpersonationSessionUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ImpersonationSessionUpdate) SetNillableStatus(v *int8) *ImpersonationSessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ImpersonationSessionUpdate) AddStatus(v int8) *ImpersonationSessionUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ImpersonationSessionUpdate) SetCreatedAt(v time.Time) *ImpersonationSessionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ImpersonationSessionUpdate) SetNillableCreatedAt(v *time.Time) *ImpersonationSessionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ImpersonationSessionUpdate) SetExpiresAt(v time.Time) *ImpersonationSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ImpersonationSessionUpdate) SetNillableExpiresAt(v *time.Time) *ImpersonationSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *ImpersonationSessionUpdate) SetRevokedAt(v time.Time) *ImpersonationSessionUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *ImpersonationSessionUpdate) SetNillableRevokedAt(v *time.Time) *ImpersonationSessionUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *ImpersonationSessionUpdate) ClearRevokedAt() *ImpersonationSessionUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the ImpersonationSessionMutation object of the builder.
func (_u *ImpersonationSessionUpdate) Mutation() *ImpersonationSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImpersonationSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImpersonationSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImpersonationSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImpersonationSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ImpersonationSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(impersonationsession.Table, impersonationsession.Columns, sqlgraph.NewFieldSpec(impersonationsession.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(impersonationsession.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(impersonationsession.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAppID(); ok {
		_spec.AddField(impersonationsession.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DivisionID(); ok {
		_spec.SetField(impersonationsession.FieldDivisionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDivisionID(); ok {
		_spec.AddField(impersonationsession.FieldDivisionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ImpersonatorUserID(); ok {
		_spec.SetField(impersonationsession.FieldImpersonatorUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImpersonatorUserID(); ok {
		_spec.AddField(impersonationsession.FieldImpersonatorUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TargetUserID(); ok {
		_spec.SetField(impersonationsession.FieldTargetUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetUserID(); ok {
		_spec.AddField(impersonationsession.FieldTargetUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Audience(); ok {
		_spec.SetField(impersonationsession.FieldAudience, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReadOnly(); ok {
		_spec.SetField(impersonationsession.FieldReadOnly, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(impersonationsession.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(impersonationsession.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(impersonationsession.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(impersonationsession.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(impersonationsession.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(impersonationsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(impersonationsession.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(impersonationsession.FieldRevokedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{impersonationsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImpersonationSessionUpdateOne is the builder for updating a single ImpersonationSession entity.
type ImpersonationSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImpersonationSessionMutation
}

// SetSessionID sets the "session_id" field.
func (_u *ImpersonationSessionUpdateOne) SetSessionID(v string) *ImpersonationSessionUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *ImpersonationSessionUpdateOne) SetNillableSessionID(v *string) *ImpersonationSessionUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *ImpersonationSessionUpdateOne) SetAppID(v int) *ImpersonationSessionUpdateOne {
	_u.mutation.ResetAppID()
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *ImpersonationSessionUpdateOne) SetNillableAppID(v *int) *ImpersonationSessionUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// AddAppID adds value to the "app_id" field.
func (_u *ImpersonationSessionUpdateOne) AddAppID(v int) *ImpersonationSessionUpdateOne {
	_u.mutation.AddAppID(v)
	return _u
}

// SetDivisionID sets the "division_id" field.
func (_u *ImpersonationSessionUpdateOne) SetDivisionID(v int) *ImpersonationSessionUpdateOne {
	_u.mutation.ResetDivisionID()
	_u.mutation.SetDivisionID(v)
	return _u
}

// SetNillableDivisionID sets the "division_id" field if the given value is not nil.
func (_u *ImpersonationSessionUpdateOne) SetNillableDivisionID(v *int) *ImpersonationSessionUpdateOne {
	if v != nil {
		_u.SetDivisionID(*v)
	}
	return _u
}

// AddDivisionID adds value to the "division_id" field.
func (_u *ImpersonationSessionUpdateOne) AddDivisionID(v int) *ImpersonationSessionUpdateOne {
	_u.mutation.AddDivisionID(v)
	return _u
}

// SetImpersonatorUserID sets the "impersonator_user_id" field.
func (_u *ImpersonationSessionUpdateOne) SetImpersonatorUserID(v int) *ImpersonationSessionUpdateOne {
	_u.mutation.ResetImpersonatorUserID()
	_u.mutation.SetImpersonatorUserID(v)
	return _u
}

// SetNillableImpersonatorUserID sets the "impersonator_user_id" field if the given value is not nil.
func (_u *ImpersonationSessionUpdateOne) SetNillableImpersonatorUserID(v *int) *ImpersonationSessionUpdateOne {
	if v != nil {
		_u.SetImpersonatorUserID(*v)
	}
	return _u
}

// AddImpersonatorUserID adds value to the "impersonator_user_id" field.
func (_u *ImpersonationSessionUpdateOne) AddImpersonatorUserID(v int) *ImpersonationSessionUpdateOne {
	_u.mutation.AddImpersonatorUserID(v)
	return _u
}

// SetTargetUserID sets the "target_user_id" field.
func (_u *ImpersonationSessionUpdateOne) SetTargetUserID(v int) *ImpersonationSessionUpdateOne {
	_u.mutation.ResetTargetUserID()
	_u.mutation.SetTargetUserID(v)
	return _u
}

// SetNillableTargetUserID sets the "target_user_id" field if the given value is not nil.
func (_u *ImpersonationSessionUpdateOne) SetNillableTargetUserID(v *int) *ImpersonationSessionUpdateOne {
	if v != nil {
		_u.SetTargetUserID(*v)
	}
	return _u
}

// AddTargetUserID adds value to the "target_user_id" field.
func (_u *ImpersonationSessionUpdateOne) AddTargetUserID(v int) *ImpersonationSessionUpdateOne {
	_u.mutation.AddTargetUserID(v)
	return _u
}

// SetAudience sets the "audience" field.
func (_u *ImpersonationSessionUpdateOne) SetAudience(v string) *ImpersonationSessionUpdateOne {
	_u.mutation.SetAudience(v)
	return _u
}

// SetNillableAudience sets the "audience" field if the given value is not nil.
func (_u *ImpersonationSessionUpdateOne) SetNillableAudience(v *string) *ImpersonationSessionUpdateOne {
	if v != nil {
		_u.SetAudience(*v)
	}
	return _u
}

// SetReadOnly sets the "read_only" field.
func (_u *ImpersonationSessionUpdateOne) SetReadOnly(v bool) *ImpersonationSessionUpdateOne {
	_u.mutation.SetReadOnly(v)
	return _u
}

// SetNillableReadOnly sets the "read_only" field if the given value is not nil.
func (_u *ImpersonationSessionUpdateOne) SetNillableReadOnly(v *bool) *ImpersonationSessionUpdateOne {
	if v != nil {
		_u.SetReadOnly(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *ImpersonationSessionUpdateOne) SetReason(v string) *ImpersonationSessionUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *ImpersonationSessionUpdateOne) SetNillableReason(v *string) *ImpersonationSessionUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *ImpersonationSessionUpdateOne) ClearReason() *ImpersonationSessionUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ImpersonationSessionUpdateOne) SetStatus(v int8) *ImpersonationSessionUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ImpersonationSessionUpdateOne) SetNillableStatus(v *int8) *ImpersonationSessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *ImpersonationSessionUpdateOne) AddStatus(v int8) *ImpersonationSessionUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ImpersonationSessionUpdateOne) SetCreatedAt(v time.Time) *ImpersonationSessionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ImpersonationSessionUpdateOne) SetNillableCreatedAt(v *time.Time) *ImpersonationSessionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ImpersonationSessionUpdateOne) SetExpiresAt(v time.Time) *ImpersonationSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ImpersonationSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *ImpersonationSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *ImpersonationSessionUpdateOne) SetRevokedAt(v time.Time) *ImpersonationSessionUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *ImpersonationSessionUpdateOne) SetNillableRevokedAt(v *time.Time) *ImpersonationSessionUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *ImpersonationSessionUpdateOne) ClearRevokedAt() *ImpersonationSessionUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the ImpersonationSessionMutation object of the builder.
func (_u *ImpersonationSessionUpdateOne) Mutation() *ImpersonationSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the ImpersonationSessionUpdate builder.
func (_u *ImpersonationSessionUpdateOne) Where(ps ...predicate.ImpersonationSession) *ImpersonationSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImpersonationSessionUpdateOne) Select(field string, fields ...string) *ImpersonationSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImpersonationSession entity.
func (_u *ImpersonationSessionUpdateOne) Save(ctx context.Context) (*ImpersonationSession, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImpersonationSessionUpdateOne) SaveX(ctx context.Context) *ImpersonationSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImpersonationSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImpersonationSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ImpersonationSessionUpdateOne) sqlSave(ctx context.Context) (_node *ImpersonationSession, err error) {
	_spec := sqlgraph.NewUpdateSpec(impersonationsession.Table, impersonationsession.Columns, sqlgraph.NewFieldSpec(impersonationsession.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImpersonationSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, impersonationsession.FieldID)
		for _, f := range fields {
			if !impersonationsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != impersonationsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(impersonationsession.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(impersonationsession.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAppID(); ok {
		_spec.AddField(impersonationsession.FieldAppID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DivisionID(); ok {
		_spec.SetField(impersonationsession.FieldDivisionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDivisionID(); ok {
		_spec.AddField(impersonationsession.FieldDivisionID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ImpersonatorUserID(); ok {
		_spec.SetField(impersonationsession.FieldImpersonatorUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedImpersonatorUserID(); ok {
		_spec.AddField(impersonationsession.FieldImpersonatorUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TargetUserID(); ok {
		_spec.SetField(impersonationsession.FieldTargetUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTargetUserID(); ok {
		_spec.AddField(impersonationsession.FieldTargetUserID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Audience(); ok {
		_spec.SetField(impersonationsession.FieldAudience, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReadOnly(); ok {
		_spec.SetField(impersonationsession.FieldReadOnly, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(impersonationsession.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(impersonationsession.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(impersonationsession.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(impersonationsession.FieldStatus, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(impersonationsession.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(impersonationsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(impersonationsession.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(impersonationsession.FieldRevokedAt, field.TypeTime)
	}
	_node = &ImpersonationSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{impersonationsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
