// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"keeper/ent/impersonationsession"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ImpersonationSessionCreate is the builder for creating a ImpersonationSession entity.
type ImpersonationSessionCreate struct {
	config
	mutation *ImpersonationSessionMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (_c *ImpersonationSessionCreate) SetSessionID(v string) *ImpersonationSessionCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetAppID sets the "app_id" field.
func (_c *ImpersonationSessionCreate) SetAppID(v int) *ImpersonationSessionCreate {
	_c.mutation.SetAppID(v)
	return _c
}

// SetDivisionID sets the "division_id" field.
func (_c *ImpersonationSessionCreate) SetDivisionID(v int) *ImpersonationSessionCreate {
	_c.mutation.SetDivisionID(v)
	return _c
}

// SetImpersonatorUserID sets the "impersonator_user_id" field.
func (_c *ImpersonationSessionCreate) SetImpersonatorUserID(v int) *ImpersonationSessionCreate {
	_c.mutation.SetImpersonatorUserID(v)
	return _c
}

// SetTargetUserID sets the "target_user_id" field.
func (_c *ImpersonationSessionCreate) SetTargetUserID(v int) *ImpersonationSessionCreate {
	_c.mutation.SetTargetUserID(v)
	return _c
}

// SetAudience sets the "audience" field.
func (_c *ImpersonationSessionCreate) SetAudience(v string) *ImpersonationSessionCreate {
	_c.mutation.SetAudience(v)
	return _c
}

// SetReadOnly sets the "read_only" field.
func (_c *ImpersonationSessionCreate) SetReadOnly(v bool) *ImpersonationSessionCreate {
	_c.mutation.SetReadOnly(v)
	return _c
}

// SetNillableReadOnly sets the "read_only" field if the given value is not nil.
func (_c *ImpersonationSessionCreate) SetNillableReadOnly(v *bool) *ImpersonationSessionCreate {
	if v != nil {
		_c.SetReadOnly(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *ImpersonationSessionCreate) SetReason(v string) *ImpersonationSessionCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *ImpersonationSessionCreate) SetNillableReason(v *string) *ImpersonationSessionCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ImpersonationSessionCreate) SetStatus(v int8) *ImpersonationSessionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ImpersonationSessionCreate) SetNillableStatus(v *int8) *ImpersonationSessionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ImpersonationSessionCreate) SetCreatedAt(v time.Time) *ImpersonationSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ImpersonationSessionCreate) SetNillableCreatedAt(v *time.Time) *ImpersonationSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ImpersonationSessionCreate) SetExpiresAt(v time.Time) *ImpersonationSessionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *ImpersonationSessionCreate) SetRevokedAt(v time.Time) *ImpersonationSessionCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *ImpersonationSessionCreate) SetNillableRevokedAt(v *time.Time) *ImpersonationSessionCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// Mutation returns the ImpersonationSessionMutation object of the builder.
func (_c *ImpersonationSessionCreate) Mutation() *ImpersonationSessionMutation {
	return _c.mutation
}

// Save creates the ImpersonationSession in the database.
func (_c *ImpersonationSessionCreate) Save(ctx context.Context) (*ImpersonationSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImpersonationSessionCreate) SaveX(ctx context.Context) *ImpersonationSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImpersonationSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImpersonationSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImpersonationSessionCreate) defaults() {
	if _, ok := _c.mutation.ReadOnly(); !ok {
		v := impersonationsession.DefaultReadOnly
		_c.mutation.SetReadOnly(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := impersonationsession.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := impersonationsession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImpersonationSessionCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "ImpersonationSession.session_id"`)}
	}
	if _, ok := _c.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "ImpersonationSession.app_id"`)}
	}
	if _, ok := _c.mutation.DivisionID(); !ok {
		return &ValidationError{Name: "division_id", err: errors.New(`ent: missing required field "ImpersonationSession.division_id"`)}
	}
	if _, ok := _c.mutation.ImpersonatorUserID(); !ok {
		return &ValidationError{Name: "impersonator_user_id", err: errors.New(`ent: missing required field "ImpersonationSession.impersonator_user_id"`)}
	}
	if _, ok := _c.mutation.TargetUserID(); !ok {
		return &ValidationError{Name: "target_user_id", err: errors.New(`ent: missing required field "ImpersonationSession.target_user_id"`)}
	}
	if _, ok := _c.mutation.Audience(); !ok {
		return &ValidationError{Name: "audience", err: errors.New(`ent: missing required field "ImpersonationSession.audience"`)}
	}
	if _, ok := _c.mutation.ReadOnly(); !ok {
		return &ValidationError{Name: "read_only", err: errors.New(`ent: missing required field "ImpersonationSession.read_only"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ImpersonationSession.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ImpersonationSession.created_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "ImpersonationSession.expires_at"`)}
	}
	return nil
}

func (_c *ImpersonationSessionCreate) sqlSave(ctx context.Context) (*ImpersonationSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImpersonationSessionCreate) createSpec() (*ImpersonationSession, *sqlgraph.CreateSpec) {
	var (
		_node = &ImpersonationSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(impersonationsession.Table, sqlgraph.NewFieldSpec(impersonationsession.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(impersonationsession.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.AppID(); ok {
		_spec.SetField(impersonationsession.FieldAppID, field.TypeInt, value)
		_node.AppID = value
	}
	if value, ok := _c.mutation.DivisionID(); ok {
		_spec.SetField(impersonationsession.FieldDivisionID, field.TypeInt, value)
		_node.DivisionID = value
	}
	if value, ok := _c.mutation.ImpersonatorUserID(); ok {
		_spec.SetField(impersonationsession.FieldImpersonatorUserID, field.TypeInt, value)
		_node.ImpersonatorUserID = value
	}
	if value, ok := _c.mutation.TargetUserID(); ok {
		_spec.SetField(impersonationsession.FieldTargetUserID, field.TypeInt, value)
		_node.TargetUserID = value
	}
	if value, ok := _c.mutation.Audience(); ok {
		_spec.SetField(impersonationsession.FieldAudience, field.TypeString, value)
		_node.Audience = value
	}
	if value, ok := _c.mutation.ReadOnly(); ok {
		_spec.SetField(impersonationsession.FieldReadOnly, field.TypeBool, value)
		_node.ReadOnly = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(impersonationsession.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(impersonationsession.FieldStatus, field.TypeInt8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(impersonationsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(impersonationsession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(impersonationsession.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	return _node, _spec
}

// ImpersonationSessionCreateBulk is the builder for creating many ImpersonationSession entities in bulk.
type ImpersonationSessionCreateBulk struct {
	config
	err      error
	builders []*ImpersonationSessionCreate
}

// Save creates the ImpersonationSession entities in the database.
func (_c *ImpersonationSessionCreateBulk) Save(ctx context.Context) ([]*ImpersonationSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ImpersonationSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImpersonationSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImpersonationSessionCreateBulk) SaveX(ctx context.Context) []*ImpersonationSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImpersonationSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImpersonationSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
