// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"keeper/ent/impersonationsession"
	"keeper/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ImpersonationSessionDelete is the builder for deleting a ImpersonationSession entity.
type ImpersonationSessionDelete struct {
	config
	hooks    []Hook
	mutation *ImpersonationSessionMutation
}

// Where appends a list predicates to the ImpersonationSessionDelete builder.
func (_d *ImpersonationSessionDelete) Where(ps ...predicate.ImpersonationSession) *ImpersonationSessionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ImpersonationSessionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ImpersonationSessionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ImpersonationSessionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(impersonationsession.Table, sqlgraph.NewFieldSpec(impersonationsession.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ImpersonationSessionDeleteOne is the builder for deleting a single ImpersonationSession entity.
type ImpersonationSessionDeleteOne struct {
	_d *ImpersonationSessionDelete
}

// Where appends a list predicates to the ImpersonationSessionDelete builder.
func (_d *ImpersonationSessionDeleteOne) Where(ps ...predicate.ImpersonationSession) *ImpersonationSessionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ImpersonationSessionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{impersonationsession.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ImpersonationSessionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
