// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"keeper/ent/impersonationsession"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ImpersonationSession is the model entity for the ImpersonationSession schema.
type ImpersonationSession struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// SessionID holds the value of the "session_id" field.
	SessionID string `json:"session_id,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID int `json:"app_id,omitempty"`
	// DivisionID holds the value of the "division_id" field.
	DivisionID int `json:"division_id,omitempty"`
	// ImpersonatorUserID holds the value of the "impersonator_user_id" field.
	ImpersonatorUserID int `json:"impersonator_user_id,omitempty"`
	// TargetUserID holds the value of the "target_user_id" field.
	TargetUserID int `json:"target_user_id,omitempty"`
	// Audience holds the value of the "audience" field.
	Audience string `json:"audience,omitempty"`
	// ReadOnly holds the value of the "read_only" field.
	ReadOnly bool `json:"read_only,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// Status holds the value of the "status" field.
	Status int8 `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// RevokedAt holds the value of the "revoked_at" field.
	RevokedAt    *time.Time `json:"revoked_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImpersonationSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case impersonationsession.FieldReadOnly:
			values[i] = new(sql.NullBool)
		case impersonationsession.FieldID, impersonationsession.FieldAppID, impersonationsession.FieldDivisionID, impersonationsession.FieldImpersonatorUserID, impersonationsession.FieldTargetUserID, impersonationsession.FieldStatus:
			values[i] = new(sql.NullInt64)
		case impersonationsession.FieldSessionID, impersonationsession.FieldAudience, impersonationsession.FieldReason:
			values[i] = new(sql.NullString)
		case impersonationsession.FieldCreatedAt, impersonationsession.FieldExpiresAt, impersonationsession.FieldRevokedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImpersonationSession fields.
func (_m *ImpersonationSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case impersonationsession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case impersonationsession.FieldSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_id", values[i])
			} else if value.Valid {
				_m.SessionID = value.String
			}
		case impersonationsession.FieldAppID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value.Valid {
				_m.AppID = int(value.Int64)
			}
		case impersonationsession.FieldDivisionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field division_id", values[i])
			} else if value.Valid {
				_m.DivisionID = int(value.Int64)
			}
		case impersonationsession.FieldImpersonatorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field impersonator_user_id", values[i])
			} else if value.Valid {
				_m.ImpersonatorUserID = int(value.Int64)
			}
		case impersonationsession.FieldTargetUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_user_id", values[i])
			} else if value.Valid {
				_m.TargetUserID = int(value.Int64)
			}
		case impersonationsession.FieldAudience:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field audience", values[i])
			} else if value.Valid {
				_m.Audience = value.String
			}
		case impersonationsession.FieldReadOnly:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field read_only", values[i])
			} else if value.Valid {
				_m.ReadOnly = value.Bool
			}
		case impersonationsession.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case impersonationsession.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int8(value.Int64)
			}
		case impersonationsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case impersonationsession.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case impersonationsession.FieldRevokedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field revoked_at", values[i])
			} else if value.Valid {
				_m.RevokedAt = new(time.Time)
				*_m.RevokedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImpersonationSession.
// This includes values selected through modifiers, order, etc.
func (_m *ImpersonationSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ImpersonationSession.
// Note that you need to call ImpersonationSession.Unwrap() before calling this method if this ImpersonationSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImpersonationSession) Update() *ImpersonationSessionUpdateOne {
	return NewImpersonationSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImpersonationSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImpersonationSession) Unwrap() *ImpersonationSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImpersonationSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImpersonationSession) String() string {
	var builder strings.Builder
	builder.WriteString("ImpersonationSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("session_id=")
	builder.WriteString(_m.SessionID)
	builder.WriteString(", ")
	builder.WriteString("app_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AppID))
	builder.WriteString(", ")
	builder.WriteString("division_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DivisionID))
	builder.WriteString(", ")
	builder.WriteString("impersonator_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ImpersonatorUserID))
	builder.WriteString(", ")
	builder.WriteString("target_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetUserID))
	builder.WriteString(", ")
	builder.WriteString("audience=")
	builder.WriteString(_m.Audience)
	builder.WriteString(", ")
	builder.WriteString("read_only=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReadOnly))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.RevokedAt; v != nil {
		builder.WriteString("revoked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ImpersonationSessions is a parsable slice of ImpersonationSession.
type ImpersonationSessions []*ImpersonationSession
