// Code generated by ent, DO NOT EDIT.

package ent

import (
	"keeper/ent/app"
	"keeper/ent/division"
	"keeper/ent/guestkey"
	"keeper/ent/impersonationsession"
	"keeper/ent/schema"
	"keeper/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appFields := schema.App{}.Fields()
	_ = appFields
	// appDescCurrency is the schema descriptor for currency field.
	appDescCurrency := appFields[17].Descriptor()
	// app.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	app.CurrencyValidator = func() func(string) error {
		validators := appDescCurrency.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(currency string) error {
			for _, fn := range fns {
				if err := fn(currency); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// appDescTaxPercent is the schema descriptor for tax_percent field.
	appDescTaxPercent := appFields[18].Descriptor()
	// app.DefaultTaxPercent holds the default value on creation for the tax_percent field.
	app.DefaultTaxPercent = appDescTaxPercent.Default.(float64)
	// appDescStatus is the schema descriptor for status field.
	appDescStatus := appFields[20].Descriptor()
	// app.DefaultStatus holds the default value on creation for the status field.
	app.DefaultStatus = appDescStatus.Default.(int8)
	// appDescCreatedAt is the schema descriptor for created_at field.
	appDescCreatedAt := appFields[21].Descriptor()
	// app.DefaultCreatedAt holds the default value on creation for the created_at field.
	app.DefaultCreatedAt = appDescCreatedAt.Default.(func() time.Time)
	// appDescUpdatedAt is the schema descriptor for updated_at field.
	appDescUpdatedAt := appFields[22].Descriptor()
	// app.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	app.DefaultUpdatedAt = appDescUpdatedAt.Default.(func() time.Time)
	// app.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	app.UpdateDefaultUpdatedAt = appDescUpdatedAt.UpdateDefault.(func() time.Time)
	divisionFields := schema.Division{}.Fields()
	_ = divisionFields
	// divisionDescDepth is the schema descriptor for depth field.
	divisionDescDepth := divisionFields[4].Descriptor()
	// division.DefaultDepth holds the default value on creation for the depth field.
	division.DefaultDepth = divisionDescDepth.Default.(int8)
	// divisionDescStatus is the schema descriptor for status field.
	divisionDescStatus := divisionFields[5].Descriptor()
	// division.DefaultStatus holds the default value on creation for the status field.
	division.DefaultStatus = divisionDescStatus.Default.(int8)
	// divisionDescCreatedAt is the schema descriptor for created_at field.
	divisionDescCreatedAt := divisionFields[6].Descriptor()
	// division.DefaultCreatedAt holds the default value on creation for the created_at field.
	division.DefaultCreatedAt = divisionDescCreatedAt.Default.(func() time.Time)
	// divisionDescUpdatedAt is the schema descriptor for updated_at field.
	divisionDescUpdatedAt := divisionFields[7].Descriptor()
	// division.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	division.DefaultUpdatedAt = divisionDescUpdatedAt.Default.(func() time.Time)
	// division.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	division.UpdateDefaultUpdatedAt = divisionDescUpdatedAt.UpdateDefault.(func() time.Time)
	guestkeyFields := schema.GuestKey{}.Fields()
	_ = guestkeyFields
	// guestkeyDescStatus is the schema descriptor for status field.
	guestkeyDescStatus := guestkeyFields[6].Descriptor()
	// guestkey.DefaultStatus holds the default value on creation for the status field.
	guestkey.DefaultStatus = guestkeyDescStatus.Default.(int8)
	// guestkeyDescCreatedAt is the schema descriptor for created_at field.
	guestkeyDescCreatedAt := guestkeyFields[7].Descriptor()
	// guestkey.DefaultCreatedAt holds the default value on creation for the created_at field.
	guestkey.DefaultCreatedAt = guestkeyDescCreatedAt.Default.(func() time.Time)
	// guestkeyDescUpdatedAt is the schema descriptor for updated_at field.
	guestkeyDescUpdatedAt := guestkeyFields[8].Descriptor()
	// guestkey.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	guestkey.DefaultUpdatedAt = guestkeyDescUpdatedAt.Default.(func() time.Time)
	// guestkey.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	guestkey.UpdateDefaultUpdatedAt = guestkeyDescUpdatedAt.UpdateDefault.(func() time.Time)
	impersonationsessionFields := schema.ImpersonationSession{}.Fields()
	_ = impersonationsessionFields
	// impersonationsessionDescReadOnly is the schema descriptor for read_only field.
	impersonationsessionDescReadOnly := impersonationsessionFields[6].Descriptor()
	// impersonationsession.DefaultReadOnly holds the default value on creation for the read_only field.
	impersonationsession.DefaultReadOnly = impersonationsessionDescReadOnly.Default.(bool)
	// impersonationsessionDescStatus is the schema descriptor for status field.
	impersonationsessionDescStatus := impersonationsessionFields[8].Descriptor()
	// impersonationsession.DefaultStatus holds the default value on creation for the status field.
	impersonationsession.DefaultStatus = impersonationsessionDescStatus.Default.(int8)
	// impersonationsessionDescCreatedAt is the schema descriptor for created_at field.
	impersonationsessionDescCreatedAt := impersonationsessionFields[9].Descriptor()
	// impersonationsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	impersonationsession.DefaultCreatedAt = impersonationsessionDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[6].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(int8)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[7].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(int8)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[8].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[9].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
