// Code generated by ent, DO NOT EDIT.

package app

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the app type in the database.
	Label = "app"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldTagline holds the string denoting the tagline field in the database.
	FieldTagline = "tagline"
	// FieldLogoURL holds the string denoting the logo_url field in the database.
	FieldLogoURL = "logo_url"
	// FieldAboutHeading holds the string denoting the about_heading field in the database.
	FieldAboutHeading = "about_heading"
	// FieldAboutBody holds the string denoting the about_body field in the database.
	FieldAboutBody = "about_body"
	// FieldContactAddressLine1 holds the string denoting the contact_address_line1 field in the database.
	FieldContactAddressLine1 = "contact_address_line1"
	// FieldContactAddressLine2 holds the string denoting the contact_address_line2 field in the database.
	FieldContactAddressLine2 = "contact_address_line2"
	// FieldContactCity holds the string denoting the contact_city field in the database.
	FieldContactCity = "contact_city"
	// FieldContactState holds the string denoting the contact_state field in the database.
	FieldContactState = "contact_state"
	// FieldContactCountry holds the string denoting the contact_country field in the database.
	FieldContactCountry = "contact_country"
	// FieldContactPostalCode holds the string denoting the contact_postal_code field in the database.
	FieldContactPostalCode = "contact_postal_code"
	// FieldContactPhone1 holds the string denoting the contact_phone1 field in the database.
	FieldContactPhone1 = "contact_phone1"
	// FieldContactPhone2 holds the string denoting the contact_phone2 field in the database.
	FieldContactPhone2 = "contact_phone2"
	// FieldContactEmail holds the string denoting the contact_email field in the database.
	FieldContactEmail = "contact_email"
	// FieldContactHours holds the string denoting the contact_hours field in the database.
	FieldContactHours = "contact_hours"
	// FieldContactSocial holds the string denoting the contact_social field in the database.
	FieldContactSocial = "contact_social"
	// FieldTaxNumber holds the string denoting the tax_number field in the database.
	FieldTaxNumber = "tax_number"
	// FieldTaxPercent holds the string denoting the tax_percent field in the database.
	FieldTaxPercent = "tax_percent"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUsers holds the string denoting the users edge name in mutations.
	EdgeUsers = "users"
	// EdgeDivisions holds the string denoting the divisions edge name in mutations.
	EdgeDivisions = "divisions"
	// Table holds the table name of the app in the database.
	Table = "kpr_app"
	// UsersTable is the table that holds the users relation/edge.
	UsersTable = "kpr_user"
	// UsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UsersInverseTable = "kpr_user"
	// UsersColumn is the table column denoting the users relation/edge.
	UsersColumn = "app_id"
	// DivisionsTable is the table that holds the divisions relation/edge.
	DivisionsTable = "kpr_division"
	// DivisionsInverseTable is the table name for the Division entity.
	// It exists in this package in order to avoid circular dependency with the "division" package.
	DivisionsInverseTable = "kpr_division"
	// DivisionsColumn is the table column denoting the divisions relation/edge.
	DivisionsColumn = "app_id"
)

// Columns holds all SQL columns for app fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldTagline,
	FieldLogoURL,
	FieldAboutHeading,
	FieldAboutBody,
	FieldContactAddressLine1,
	FieldContactAddressLine2,
	FieldContactCity,
	FieldContactState,
	FieldContactCountry,
	FieldContactPostalCode,
	FieldContactPhone1,
	FieldContactPhone2,
	FieldContactEmail,
	FieldContactHours,
	FieldContactSocial,
	FieldTaxNumber,
	FieldTaxPercent,
	FieldStatus,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTaxPercent holds the default value on creation for the "tax_percent" field.
	DefaultTaxPercent float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int8
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the App queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByTagline orders the results by the tagline field.
func ByTagline(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTagline, opts...).ToFunc()
}

// ByLogoURL orders the results by the logo_url field.
func ByLogoURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogoURL, opts...).ToFunc()
}

// ByAboutHeading orders the results by the about_heading field.
func ByAboutHeading(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAboutHeading, opts...).ToFunc()
}

// ByAboutBody orders the results by the about_body field.
func ByAboutBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAboutBody, opts...).ToFunc()
}

// ByContactAddressLine1 orders the results by the contact_address_line1 field.
func ByContactAddressLine1(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactAddressLine1, opts...).ToFunc()
}

// ByContactAddressLine2 orders the results by the contact_address_line2 field.
func ByContactAddressLine2(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactAddressLine2, opts...).ToFunc()
}

// ByContactCity orders the results by the contact_city field.
func ByContactCity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactCity, opts...).ToFunc()
}

// ByContactState orders the results by the contact_state field.
func ByContactState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactState, opts...).ToFunc()
}

// ByContactCountry orders the results by the contact_country field.
func ByContactCountry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactCountry, opts...).ToFunc()
}

// ByContactPostalCode orders the results by the contact_postal_code field.
func ByContactPostalCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactPostalCode, opts...).ToFunc()
}

// ByContactPhone1 orders the results by the contact_phone1 field.
func ByContactPhone1(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactPhone1, opts...).ToFunc()
}

// ByContactPhone2 orders the results by the contact_phone2 field.
func ByContactPhone2(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactPhone2, opts...).ToFunc()
}

// ByContactEmail orders the results by the contact_email field.
func ByContactEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactEmail, opts...).ToFunc()
}

// ByContactHours orders the results by the contact_hours field.
func ByContactHours(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContactHours, opts...).ToFunc()
}

// ByTaxNumber orders the results by the tax_number field.
func ByTaxNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxNumber, opts...).ToFunc()
}

// ByTaxPercent orders the results by the tax_percent field.
func ByTaxPercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaxPercent, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUsersCount orders the results by users count.
func ByUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsersStep(), opts...)
	}
}

// ByUsers orders the results by users terms.
func ByUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDivisionsCount orders the results by divisions count.
func ByDivisionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDivisionsStep(), opts...)
	}
}

// ByDivisions orders the results by divisions terms.
func ByDivisions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDivisionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsersTable, UsersColumn),
	)
}
func newDivisionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DivisionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DivisionsTable, DivisionsColumn),
	)
}
